### ISSUE TITLE
Resizing Support

### ISSUE THREAD

**Issue by OpenSauce** [yohamta/furex#19]
Hi,

Currently looking at using this in a game I'm working on with a friend. Does this currently support resizing? If not do you think it would be difficult to add? I was thinking being able to pass through the window size to Update().

What're your thoughts? Thanks!

**Comment by yohamta** [comment]
Hi, thanks for the question!

I think it would be possible by adding a new method `func (v *View) UpdateWithSize(w, h int)` to the `View` struct.
If the width and height passed to this method are different from the current, the `View` instance will mark it as `isDirty = true` and call `Update()` inside the method. The user calls `UpdateWithSize(w, h int)` instead of `Update()`.

Alternatively, we could add a new `Layout()` method to dynamically update other `View` properties such as `Top` and `Left`.

What're your thoughts about this?

**Comment by OpenSauce** [comment]
Yo!

Having a look now, the update method seems to be the simplest approach, could also combine it with grow/shrink properties on the view. 

Only thing I can think of right now is that the update function:

`func (g *Game) Update() error {
	if !g.init {
		g.init = true
		g.setupUI()
	}

	g.gameUI.UpdateWithSize(ebiten.WindowSize())
	return nil
}`

Would this be something that makes more sense being handled in the Draw method? The need to call .Update() actually threw me off for a while yesterday and I was wondering why everything wasn't rendering - I can imagine there's reasons for this?

**Comment by yohamta** [comment]
I see. in that case, adding `UpdateWithSize(w, h int)` method seems right :)

> Would this be something that makes more sense being handled in the Draw method? The need to call .Update() actually threw me off for a while yesterday and I was wondering why everything wasn't rendering - I can imagine there's reasons for this?

I think the `Update()` method is better suited than the `Draw()` method in properly handling click and touch events. This is because the timing of the `Draw()` call is not at regular intervals and may be skipped due to circumstances on the game engine side.

For example, when animating the UI, the position and size calculations should be done in the `Update()` function, or else it may result in jerky behavior.

**Comment by yohamta** [comment]
@OpenSauce Thanks for the fantastic PR!

**Comment by OpenSauce** [comment]
No worries at all, happy to help where I can, you've done a lot of great work!

**Comment by yohamta** [comment]
Thank you!
